export const COURSE_STUDIO_ERROR_CODES = {
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	INVALID_MDX_CONTENT: "INVALID_MDX_CONTENT",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	UNKNOWN_ACTION: "UNKNOWN_ACTION",
} as const;

export type CourseStudioErrorCode = (typeof COURSE_STUDIO_ERROR_CODES)[keyof typeof COURSE_STUDIO_ERROR_CODES];
